language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - chmod a+x -R bin/
  - chmod a+x -R vendor/

install:
  - composer install
  - composer update

script:
  - bin/phpunit test
