language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - chmod a+x -R bin/
  - chmod a+x -R vendor/

install:
  - composer install

script:
  - bin/phpspec run --config=phpspec.yml --format=pretty
